### PR TITLE
Last Fix to Get rapp_email Passing launch_check tests in CI

### PR DESCRIPTION
**Pull request by geoffreychiou**
@130s please review.

### CODE REVIEW

**Comment by geoffreychiou** [comment]
Please merge the commits when approved.

**Review by 130s — APPROVED** [review]
I haven't tested. CI not enabled. So I only reviewed visually.

I have no right to merge on this repo.

**Comment by shaun-edwards** [comment]
@geoffreychiou, @130s, you've both been given commit rights.  Approve and merge away!

**Comment by geoffreychiou** [comment]
Thanks, hopefully I never have to touch this again!

**Pull request merged**
